version: '3'

services:

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  
  web:
    build: ./senao
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-django:/usr/src/app
    env_file: .env
    command: bash -c "python manage.py migrate && python manage.py runserver 0:8000"

volumes:
  web-django:
  pgdata:
  redisdata: