# Generated by Django 5.1.7 on 2025-03-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.URLField(max_length=2048, unique=True)),
                ('hash', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
